name: Mac OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build net6.0
      run: dotnet build --configuration Release --no-restore --framework net6.0
    - name: Test net6.0
      run: dotnet test --no-restore --verbosity minimal --framework net6.0
