name: Linux
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT : true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install mscorefonts
      run: sudo apt-get -y install ttf-mscorefonts-installer
    - name: Install dependencies
      run: dotnet restore
    - name: Build net8.0
      run: dotnet build --configuration Release --no-restore --framework net8.0
    - name: Test net8.0
      run: dotnet test --no-restore --verbosity minimal --framework net8.0
